# Generated by Django 2.1.7 on 2019-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('_id', models.CharField(blank=True, max_length=200, null=True)),
                ('_class', models.TextField(blank=True, null=True)),
                ('style', models.TextField(blank=True, null=True)),
                ('attributes', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('lft', models.IntegerField()),
                ('rgt', models.IntegerField()),
            ],
        ),
    ]
