# Generated by Django 2.1.7 on 2019-02-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20190222_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('_class', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
    ]
